### ISSUE TITLE
gitgutter signs not recognized

### ISSUE THREAD

**Issue by frat3rius** [kalekundert/vim-coiled-snake#16] opened 2020-03-01 21:52 UTC
This plugin https://github.com/airblade/vim-gitgutter/ puts extra sign that gives info about diffs in file. Somehow coiled-snake doesn't deal with it and cuts line when it informs about how many lines have been folded (at end of description).

It shows it in proper way when I put a mark (gitgutter usses mark column as I can tell).

Gitgutter is doing it in async way I think, and that's probably the reason coiled-snake is not peaking it up (for short time after start the line is shown correctly, when gitgutter shows diffs after a second or so, the folding comment is being cut away with one column).

**Comment by frat3rius** [comment] 2020-03-01 21:58
The same problem occurs when I use ```set signcolumn=yes```, and here gitgutter isn't putting anything in sign column, so I think it's 100% bug. I'm using latest plugins and latest neovim@archlinux.

**Comment by kalekundert** [comment] 2020-03-02 15:26
Thanks for the report.  I'll try to look into this tonight.

**Comment by kalekundert** [comment] 2020-03-07 14:36
I just pushed a commit that should solve this issue.  Basically, the code to calculate the screen width wasn't correctly accounting for the 'signcolumn' option.  Let me know if you still have any problems, though!

**Comment by frat3rius** [comment] 2020-03-08 11:30
@kalekundert Yes it does work now with `set signcolumn=yes` but doesn't work with gitgutter plugin so it doesn't work when signcolumn is dynamically set by third party plugin (I think so). Not sure how does gitgutter is using signcolumn (maybe there is something magical in it). But I had never problems in any other plugin before that's why I presume it's not doing anything in a wrong way.

This way or another if You need any feedback from my side please feel free to ask, though I'm not a vim/nvim expert what so ever, I'll try do my best.

**Comment by kalekundert** [comment] 2020-03-08 15:50
Yeah, I should've tested it with gitgutter instead of just `signcolumn=yes`.  Let me take another look...

**Comment by kalekundert** [comment] 2020-03-08 18:16
Ok, I think I've found the root of the problem, but I don't know how to fix it yet.  

When `signcolumn=auto`, the sign column will only be displayed if there are signs to show.  So in order to work out the correct window width, `coiledsnake` needs to check to see if there are any signs to show.  This problem is discussed in more detail on [StackOverflow](https://stackoverflow.com/questions/26315925/get-usable-window-width-in-vim-script/).  Ultimately, the [`:sign place`](http://vimdoc.sourceforge.net/htmldoc/sign.html) command is used to determine if there are any signs.  

For some reason, though, `:sign place` does not return the signs placed by `vim-gitgutter`.  I don't know if this is a bug with `vim` or with `vim-gitgutter`, or maybe just some async behavior I don't understand and not a bug at all.  I suspect that this may not be something that `coiledsnake` can fix, but I'll need to figure out how `vim-gitgutter` is actually setting the signs before I say that conclusively.  That'll probably take me a few weeks, though.

In the meantime, setting `signcolumn=yes` does seem to fix the problem.  So a hacky solution could be to make a key binding that toggles `signcolumn` between `yes` and `auto`.

**Comment by frat3rius** [comment] 2020-03-08 19:59
No problem it's not a must have functionality ;) (I simply thought that this is some minor glitch). I was using coiled-snake for last week with this bug and really doesn't bother me for a second.

And yes, I'm using this workaround right now. Thanks a lot for Your time and great plugin.

**Comment by subnut** [comment] 2020-08-10 16:31
@kalekundert Now that `g:coiled_snake_explicit_sign_width` is configurable, I think we should close this issue?

**Comment by frat3rius** [comment] 2020-08-17 19:23
I've switched to https://github.com/mhinz/vim-signify where I don't have this kind of problems ;).

**Comment by kalekundert** [comment] 2020-08-17 19:25
I'm glad you found a solution.  Since this doesn't sem like a coiled-snake bug, I'm going to close this issue.

**Closed as completed by kalekundert** 2020-08-17 19:25 UTC
