### ISSUE TITLE
Folds out of date after inserting new lines

### ISSUE THREAD

**Issue by subnut** [kalekundert/vim-coiled-snake#30] opened 2021-01-08 08:00 UTC
![gifcast_210108132615](https://user-images.githubusercontent.com/56714626/103989319-8d827680-51b5-11eb-89bd-97be38412c4a.gif)

Contents of `temp.py` -

```python
class GhostHTTPRequestHandler(http.server.BaseHTTPRequestHandler):
    def do_GET(self):
        parsed_url = urllib.parse.urlparse(self.path)
        path = parsed_url.path
        query = parsed_url.query

        responses_nodata = {
            "/": self._ghost_responder,
            "/version": self._version_responder,
            "/exit": self._exit_responder,
            "/kill": self._exit_responder,
            "/is_ghost_binary": self._sanity_check_responder,
        }

        responses_data = {
            "/focus": self._focus_responder,
            "/session-closed": self._session_closed_responder,
        }

        if path in responses_nodata:
            responses_nodata[path]()

        if path in responses_data:
            responses_data[path](query)

    def _ghost_responder(self):
        """
        The actual part. The browser extension is calling us.

        """

        if neovim_focused_address is None:
            # There's no neovim instance to handle our request
            return
        payload = (
            """\
{
  "ProtocolVersion": 1,
  "WebSocketPort": {%s}
}"""
            % servers.websocket_server.port
        )
        self.send_response(200)
        self.send_header("Content-Type", "application/json")
        self.end_headers()
        self.wfile.write(payload.encode("utf-8"))

    def _version_responder(self):
        """
        Somebody wants to check the version of the running server

        """
        self._respond(BUILD_VERSION)

    def _exit_responder(self):
        """
        We have been told to exit

        """
        self._respond("Exiting...")
        print(time.strftime("[%H:%M:%S]:"), "Received /exit")
        global stop_servers
        stop_servers()

    def _sanity_check_responder(self):
        """
        Somebody wants to check if this is _actually_ the correct server

        """
        self._respond("True")

    def _focus_responder(self, query_string):
        """
        A neovim instance is reporting that it has gained focus

        :param query_string str: The query part of the URL
        """
        _, address = urllib.parse.parse_qsl(query_string)[0]
        self._respond(address)
        global neovim_focused_address
        if neovim_focused_address != address:
            neovim_focused_address = address
            print(time.strftime("[%H:%M:%S]:"), f"Focus {address}")

    def _session_closed_responder(self, query_string):
        """
        A neovim instance is reporting that it has been closed

        :param query_string str: The query part of the URL
        """
        _, address = urllib.parse.parse_qsl(query_string)[0]
        self._respond(address)
        print(time.strftime("[%H:%M:%S]:"), f"{address} session closed")
        global WEBSOCKET_PER_NEOVIM_ADDRESS
        if WEBSOCKET_PER_NEOVIM_ADDRESS.__contains__(address):
            for websocket in WEBSOCKET_PER_NEOVIM_ADDRESS[address]:
                websocket.close()
            WEBSOCKET_PER_NEOVIM_ADDRESS.__delitem__(address)
        global neovim_focused_address
        if address == neovim_focused_address:
            neovim_focused_address = None

    def _respond(self, text):
        self.send_response(200)
        self.send_header("Content-Type", "text/plain")
        self.end_headers()
        self.wfile.write(text.encode("utf-8"))

```

**Comment by subnut** [comment] 2021-01-08 08:01
Note the blank folds. That's the bug. The GIF became whole-screen by mistake.

**Comment by kalekundert** [comment] 2021-01-08 12:37
Thanks for the example.  Just so I remember, the steps to reproduce the bug are:
- Open the file
- Insert a new line before the first line using `O`.

Some other observations:
- `tests/easy/class.py` has the same behavior, and is easier to debug by virtue of being very simple.
- The behavior seems to depend on which lines were actually modified:
  - `O`: All of the folds are off-by-1.
  - `I<Enter>`: The class fold is off-by-1, but the method folds are correct.
  - `zoO`: All of the folds are off-by-1 (same as `O`).
  - Using a file that starts with a blank line before the class fold:
    - `O`: All of the folds are correct.
    - `I<Enter>`: All of the folds are correct.
    - `o`: All of the folds are off-by-1.
  
  These examples show that it doesn't matter which lines are visible, but it does matter which lines were edited.
- This bug seems to manifest slightly differently for docstrings and imports.  I think this is because these folds are usually explicitly closed (which causes the buggy effect to end) while class/function folds are usually implicitly closed by the start of the next fold.
- Disabling Konfect/FastFold doesn't have any effect.
- Running `:set foldmethod=expr` fixes the folds.

This seems to be happening because vim is not asking coiled-snake to recalculate the folds after the newline is inserted.  If coiled-snake were asked, it would give the right answer (as exhibited by the output of `:call coiledsnake#DebugFolds()` immediately after inserting the new line).  Furthermore, in some cases (e.g. `I<Enter>`), vim seems to ask coiled-snake to recalculate some folds but not others.

Adding `:set foldmethod=expr` to `coiledsnake#ClearFolds()` mostly fixes this problem (the folds are still messed up while in insert mode, but are fixed automatically when you go back to normal mode).  I'm worried that it will make things really slow for big files, though, so I'm going to try living with this change for a while before pushing it to master.  If you want to give it a try as well, I pushed it to a branch named `fix-30`.  Let me know if it seems laggy.

**Comment by subnut** [comment] 2021-01-08 13:00
I tried it a bit, but it didn't seem laggy at all.
(Maybe it is due to my fairly fast processor? :shrug: )

**Comment by kalekundert** [comment] 2021-01-13 20:59
Ok, this should be fixed in master now.

**Closed as completed by kalekundert** 2021-01-13 20:59 UTC
