### ISSUE TITLE
Edge-case, wrong folding

### ISSUE THREAD

**Issue by subnut** [kalekundert/vim-coiled-snake#29] opened 2021-01-06 05:13 UTC
See GIF for demonstration -

![gifcast_210106104022](https://user-images.githubusercontent.com/56714626/103731702-cf6fb900-500b-11eb-8f7e-809f20d1b0db.gif)

Here's the code -
```python
class GhostHTTPRequestHandler(http.server.BaseHTTPRequestHandler):
    def do_GET(self):
        parsed_url = urllib.parse.urlparse(self.path)
        path = parsed_url.path
        query = parsed_url.query

        responses_nodata = {
            "/": self._ghost_responder,
            "/version": self._version_responder,
            "/exit": self._exit_responder,
            "/kill": self._exit_responder,
            "/is_ghost_binary": self._sanity_check_responder,
        }

        responses_data = {
            "/focus": self._focus_responder,
            "/session-closed": self._session_closed_responder,
        }

        if path in responses_nodata:
            responses_nodata[path]()

        if path in responses_data:
            responses_data[path](query)

    def _ghost_responder(self):
        """
        The actual part. The browser extension is calling us.

        """

        if neovim_focused_address is None:
            # There's no neovim instance to handle our request
            return
        payload = (
            """\
{
  "ProtocolVersion": 1,
  "WebSocketPort": {%s}
}"""
            % servers.websocket_server.port
        )
        self.send_response(200)
        self.send_header("Content-Type", "application/json")
        self.end_headers()
        self.wfile.write(payload.encode("utf-8"))

    def _version_responder(self):
        """
        Somebody wants to check the version of the running server

        """
        self._respond(BUILD_VERSION)

    def _exit_responder(self):
        """
        We have been told to exit

        """
        self._respond("Exiting...")
        print(time.strftime("[%H:%M:%S]:"), "Received /exit")
        global stop_servers
        stop_servers()

    def _sanity_check_responder(self):
        """
        Somebody wants to check if this is _actually_ the correct server

        """
        self._respond("True")

    def _focus_responder(self, query_string):
        """
        A neovim instance is reporting that it has gained focus

        :param query_string str: The query part of the URL
        """
        _, address = urllib.parse.parse_qsl(query_string)[0]
        self._respond(address)
        global neovim_focused_address
        if neovim_focused_address != address:
            neovim_focused_address = address
            print(time.strftime("[%H:%M:%S]:"), f"Focus {address}")

    def _session_closed_responder(self, query_string):
        """
        A neovim instance is reporting that it has been closed

        :param query_string str: The query part of the URL
        """
        _, address = urllib.parse.parse_qsl(query_string)[0]
        self._respond(address)
        print(time.strftime("[%H:%M:%S]:"), f"{address} session closed")
        global WEBSOCKET_PER_NEOVIM_ADDRESS
        if WEBSOCKET_PER_NEOVIM_ADDRESS.__contains__(address):
            for websocket in WEBSOCKET_PER_NEOVIM_ADDRESS[address]:
                websocket.close()
            WEBSOCKET_PER_NEOVIM_ADDRESS.__delitem__(address)
        global neovim_focused_address
        if address == neovim_focused_address:
            neovim_focused_address = None

    def _respond(self, text):
        self.send_response(200)
        self.send_header("Content-Type", "text/plain")
        self.end_headers()
        self.wfile.write(text.encode("utf-8"))
```

**Comment by kalekundert** [comment] 2021-01-06 05:20
Good catch.  I'll take a look at this tomorrow morning.

**Comment by subnut** [comment] 2021-01-06 05:33
> tomorrow morning

Just asking, What time is it now at your place? 
It's 11:03 here at my place.

**Comment by kalekundert** [comment] 2021-01-06 11:59
It was midnight.  I live in Boston.

**Comment by kalekundert** [comment] 2021-01-06 14:04
I took a look at this, and I don't think it'll be a simple fix.  The problem is clearly that the multiline string is being treated as a comment/docstring.  Ideally, the plugin would recognize the opening parenthesis on the previous line and understand that nothing should be folded until the closing parenthesis is found.  But without a real python parser, correctly detecting parentheses is not trivial.

The basic idea would be to count parentheses as they occur, and to avoid making folds when more opening than closing parentheses have been encountered.  This is complicated by the fact that it's not uncommon for parentheses to occur in strings.  Ignoring these parentheses would require detecting strings, which in turn would require accounting for the fact that strings can contain escaped delimiters.  I initially thought that f-strings would complicate this even more, but on second thought I don't think they will.

I think the best way to go about this is to modify `s:InitLine()` to calculate a "de-stringed" version of each line.  This would look something like:
```
let str_open = '\v[bB]?[fF]?[rR]?[uU]?(''|"|''''''|""")'
let str_contents = '.*'
" https://stackoverflow.com/questions/42598040/python-regex-for-matching-odd-number-of-consecutive-backslashes
let str_close = '(\\)@!(\\\\)*(\\)@!\1'
let line.text_destringed = substitute(line.text, str_open.str_contents.str_close, '', 'g')
```
Then the parentheses in `text_destringed` could be counted simply, and logic similar to that used for multiline strings could make sure that folds within parentheses are ignored:
```
let a:state.inside_paren -= count(line.text_destringed, ')')
let a:state.inside_paren -= count(line.text_destringed, ']')
let a:state.inside_paren -= count(line.text_destringed, '}')

if a:state.inside_paren < 0
    let line.is_code = 0
    return line
endif

" Count opening parentheses after the conditional, so that the line with the first parenthesis can still be folded:
let a:state.inside_paren += count(line.text_destringed, '(')
let a:state.inside_paren += count(line.text_destringed, '[')
let a:state.inside_paren += count(line.text_destringed, '{')
```
I think that should handle every case correctly, but let me know you notice anything I'm overlooking.  I don't have time to implement and test this today, but I'll try to get around to it (or at least post an update) over the weekend.

Some other miscellaneous thoughts:
- Making this change would also simplify `CloseImport()`, which currently implements a version of this algorithm that doesn't need to account for the possibility of parentheses in strings. 
- The approach of marking parenthesized lines as "not code" isn't compatible with having nested data structure folds.  Such folds currently aren't supported anyways, but they are a feature I'd like to add (now that I think about it).  Rather than using `line.is_code`, it might be better to define a new variable (e.g. `line.paren_level`) for keeping track of parentheses.

**Closed as completed** 2021-01-06 21:29 UTC

**Comment by kalekundert** [comment] 2021-01-06 21:32
Ok, I just pushed some code that should fix this bug.  All of the tests pass, but this was a pretty big change, so let me know if you notice any breakages.
